//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMahasiswa.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MahasiswaDBEntities : DbContext
    {
        public MahasiswaDBEntities()
            : base("name=MahasiswaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Falkuta> Falkutas { get; set; }
        public virtual DbSet<Jurusan> Jurusans { get; set; }
        public virtual DbSet<Mahasiswa> Mahasiswas { get; set; }
        public virtual DbSet<Masterdata> Masterdatas { get; set; }
        public virtual DbSet<Matakuliah> Matakuliahs { get; set; }
    }
}
