//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMahasiswa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mahasiswa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mahasiswa()
        {
            this.Masterdatas = new HashSet<Masterdata>();
            this.Falkutas = new HashSet<Falkuta>();
            this.jurusan = new HashSet<Jurusan>();
            this.matakuliah = new HashSet<Matakuliah>();
        }
    
        public int MahasiswaID { get; set; }
        public string Id_mhs { get; set; }
        public string Nama_mhs { get; set; }
        public string Id_falkutas { get; set; }
        public string Id_jurusan { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Masterdata> Masterdatas { get; set; }
        public virtual ICollection<Falkuta> Falkutas { get; set; }
        public virtual ICollection<Jurusan> jurusan { get; set; }
        public virtual ICollection<Matakuliah> matakuliah { get; set; }
    }
}
