//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMahasiswa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masterdata
    {
        public int MasterdataID { get; set; }
        public Nullable<int> MahasiswaID { get; set; }
        public Nullable<int> FalkutasID { get; set; }
        public Nullable<int> JurusanID { get; set; }
        public Nullable<int> MatakuliahID { get; set; }
    
        public virtual Falkuta Falkuta { get; set; }
        public virtual Jurusan Jurusan { get; set; }
        public virtual Mahasiswa Mahasiswa { get; set; }
        public virtual Matakuliah Matakuliah { get; set; }


    }
}
